version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Paris"
    reviewers:
      - "LucasLaurens"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "chore: [composer] "
    labels:
      - "back"
      - "update"
      - "composer"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Paris"
    reviewers:
      - "LucasLaurens"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "chore: [workflows] "
    labels:
      - "back"
      - "update"
      - "workflows"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
