version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "Updating Composer packages: "
    labels:
      - "back"
      - "chore"
      - "devops"
      - "enhancement"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
