name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.3', '8.2']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
        tools: composer:v2
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Rector Cache
      uses: actions/cache@v3
      with:
        path: /tmp/rector
        key: ${{ runner.os }}-rector-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-rector-

    - run: mkdir -p /tmp/rector

    - name: Run Rector
      run: composer rector process --dry-run --config=rector.php

    - name: Run PHPStan
      run: composer stan analyse -c phpstan.neon

    - name: Run Pest
      run: composer pest --parallel
